### ISSUE TITLE
Bulls and cows 문제 풀기 Fork 후 작업 진행 문제점

### ISSUE THREAD

**Issue by comnori** [yeardream23/yeardream23#3]
현재 폴더 구조나 파일 이름의 형태의 기준이 없기 때문에

향후 Pull Request 시 충돌 또는 정리가 힘들 것으로 예상됨.

이에 본인이 사용하는 gmail의 ID 로 폴더 생성하는 것을 건의

**Comment by jiunkoo** [comment]
본인 좌석명에 아이디를 결합하는 것을 건의합니다.
ex) 
이름: 구지운
좌석: c22
메일: jiunkoo0106@gmail.com
폴더명: c22_jiunkoo0106

**Comment by sunkorr** [comment]
기능 상세 내용 업데이트 되었습니다. 한번씩 확인해주세요! 5월2일 14시12분경

**Comment by comnori** [comment]
팀장님 의견에 따라서 이 Issue 반영하지 않는 것으로 종료되었습니다.

**Comment by sunkorr** [comment]
프로젝트 코드를 모을 파일을 만들었습니다. 
확인하신분들은 이모티콘 눌러주세요!
https://github.com/yeardream23/yeardream23/blob/main/ballcows/ball.ipynb
